pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                git branch: 'main', credentialsId:'github-token', 
                url:'https://github.com/iuiwiff/test_jenkins2.git'
            }
        }
    }
}